### ISSUE TITLE
이슈가 아닌 jui-base.js의 globalClass에 대해 궁금한점 있어서..

### ISSUE THREAD

**Issue by metocherry** [juijs/jui-core#13]
이슈가 아닌 궁금한점인데 어디에 써야 할지 몰라서 우선 여기에 올리게 되었습니다

jui-core가 어떻게 구현되었는지 궁금해서 jui-base.js 파일을 보게 되었습니다. 파일에 지역변수로 globalClass 객체가 있는데, 이 객체가 클로저 구현되어 include나 ready함수가 아니면 접근이 안되는 방법으로 구현되어있는 것 같습니다.

제가 분석한게 맞다면 globalClass는 자주 사용하는 객체인 것 같은데, 클로저로 구현된 것과 직접 jui객체에 할당하는 방법과 성능상에서 차이가 있는지 궁금합니다.

그리고 jui ui 프레임워크의 목표가 ui에 제한 되어있는 건가요? 아니면 angular나 ember처럼 프론트에 대한 전체적인 관리를 목표로 하고있는 건가요?

**Comment by seogi1004** [comment]
1. 모듈 간의 상속을 지원하기 위해 저런 식으로 구현한 것입니다. 관련해서 성능에 대한 고려는 하지 않았습니다. ㅎㅎ
2. Angular와 달리 JUI는 전체가 아닌 하나의 컴포넌트 단위로 웹 페이지를 구성합니다. 즉, 전체 흐름에 대한 관여는 하지 않는다는 것이 Angluar와 큰 차이점입니다. 그래서 JUI는 필요한 컴포넌트만 다시 빌드하여 독립적으로 사용할 수도 있습니다. 프로젝트를 분리한 것도 그러한 이유입니다.

정리하자면 JUI는 웹 페이지를 구성하는 요소. 즉, 컴포넌트를 잘 만들 수 있는 프레임워크라고 생각하시면 됩니다. 요즘은 차트 쪽을 많이 밀고 있죠. ㅎㅎ

**Comment by metocherry** [comment]
그렇군요. 답변 감사합니다~

**Comment by seogi1004** [comment]
@metocherry 관심 가져주셔서 감사합니다!
자주 놀러오세용!
